import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { checkout } from '../../checkout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>KJeM Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          KJeM Store Assets
        </h1>

        <div className={styles.grid}>
            <a className='styles.card'>
            <Image src="/images/Screenshot 2022-09-12 at 18.51.16.png" alt="kjem01" width={250} height={400}/>
            <p>IAmGroot T-shirt</p>
            <p>Price: 7.00 USD</p>
            <p>Available in different colors and sizes</p>
            <button onClick={(()=>{
              checkout({
                lineItems:[
                  {
                    price: "price_1M2WvKHUF3QNRiEQC00GdczI",
                    quantity:1
                  }
                ]
              })
            })}>BUY</button>
            </a>
          
          <a className='styles.card'>
          <Image src="/images/Screenshot 2022-09-15 at 00.46.45.png" alt="kjem02" width={250} height={400}/>
          <p>MIH T-shirt</p>
          <p>Price: 7.00 USD</p>
          <p>Aailable in different colors and sizes</p>
          </a>
        </div>

          <div className={styles.grid}>
          <a className='styles.card'>
            <Image src="/images/Screenshot 2022-09-15 at 00.47.23.png" alt="kjem03" width={250} height={400}/>
            <p>MIH T-shirt in black</p>
            <p>Price: 7.00 USD</p>
            <p>Aailable in different colors and sizes</p>
            </a>
            <a className='styles.card'>
            <Image src="/images/Screenshot 2022-09-15 at 00.48.22.png" alt="kjem04" width={250} height={400}/>
            <p>JGS T-shirt</p>
            <p>Price: 7.00 USD</p>
            <p>Aailable in different colors and sizes</p>
            </a>
          </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
